language: php
php:
  - 5.4
before_script:
  - mysql -e "create database IF NOT EXISTS test;" -u root
  - echo -e "[mysql]\nhost = \"localhost\"\nusername = \"root\"\npassword = \"\"\ndatabase = \"test\"" > config.ini
  - make
